# Generated by Django 3.1.1 on 2020-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textAnimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textanimation', models.CharField(blank=True, max_length=500)),
                ('textanimationI', models.CharField(blank=True, max_length=500)),
                ('textanimationII', models.CharField(blank=True, max_length=500)),
                ('textanimationIV', models.CharField(blank=True, max_length=500)),
                ('textanimationV', models.CharField(blank=True, max_length=500)),
                ('textanimationVI', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
