# Generated by Django 3.1.1 on 2020-09-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textanimation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textanimation',
            old_name='textanimation',
            new_name='animation',
        ),
        migrations.RenameField(
            model_name='textanimation',
            old_name='textanimationI',
            new_name='animationI',
        ),
        migrations.RenameField(
            model_name='textanimation',
            old_name='textanimationII',
            new_name='animationII',
        ),
        migrations.RenameField(
            model_name='textanimation',
            old_name='textanimationIV',
            new_name='animationIV',
        ),
        migrations.RenameField(
            model_name='textanimation',
            old_name='textanimationV',
            new_name='animationV',
        ),
        migrations.RenameField(
            model_name='textanimation',
            old_name='textanimationVI',
            new_name='animationVI',
        ),
    ]
