# Generated by Django 3.1.1 on 2020-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textanimation', '0002_auto_20200905_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanimation',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
