# Generated by Django 3.1.1 on 2020-09-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('header', models.CharField(max_length=250)),
                ('bio', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
    ]
