# Generated by Django 3.1.1 on 2020-09-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200905_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='icons',
        ),
    ]
