# Generated by Django 3.1.1 on 2020-09-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200905_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='bio',
        ),
    ]
