# Generated by Django 3.1.1 on 2020-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='descriptionI',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='descriptionII',
            field=models.TextField(blank=True),
        ),
    ]
