# Generated by Django 3.1.1 on 2020-09-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_imageheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_img_Text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_img_TextI',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_img_TextII',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_img_TextIII',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_img_TextIV',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hero_img_TextV',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
