# Generated by Django 3.1.1 on 2020-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200905_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img_Text', models.CharField(blank=True, max_length=500)),
                ('hero_img_TextI', models.CharField(blank=True, max_length=500)),
                ('hero_img_TextII', models.CharField(blank=True, max_length=500)),
                ('hero_img_TextIII', models.CharField(blank=True, max_length=500)),
                ('hero_img_TextIV', models.CharField(blank=True, max_length=500)),
                ('hero_img_TextV', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hero_img_Text',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hero_img_TextI',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hero_img_TextII',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hero_img_TextIII',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hero_img_TextIV',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='hero_img_TextV',
        ),
    ]
