# Generated by Django 3.1.1 on 2020-09-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200905_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='heroImg',
        ),
    ]
